// ruleRegistry.js — declarative definitions of every editable international
// commerce table. One generic, validated, audited CRUD API (adminRoutes.js)
// and one generic admin UI are driven from these definitions.
const CC = { type: "country" };
const EN = (options) => ({ type: "enum", options });
const STATUS = EN(["confirmed", "planning", "requires_verification"]);

const ENTITIES = {
  countries: {
    table: "countries", pk: "code", pkType: "string", label: "Countries", orderBy: "sort_order, name",
    fields: {
      code: { label: "ISO code", type: "text", pattern: "^[A-Z]{2}$", required: true, createOnly: true },
      name: { label: "Name", type: "text", required: true, max: 100 },
      native_name: { label: "Local name", type: "text", max: 100 },
      default_language: { label: "Language", type: "language", required: true },
      default_currency: { label: "Default currency", type: "currency", required: true },
      shipping_zone: { label: "Shipping zone", type: "zone" },
      tax_zone: { label: "Tax zone", type: "text", max: 30 },
      customs_zone: { label: "Customs zone", type: "text", max: 30 },
      default_incoterm: { label: "Default Incoterm", type: "incoterm", required: true },
      unconfigured_charges: { label: "When charges are not configured", ...EN(["quote", "checkout"]), required: true },
      requires_tax_id: { label: "Tax ID required at checkout", type: "bool" },
      tax_id_label: { label: "Tax ID label", type: "text", max: 40 },
      sort_order: { label: "Display order", type: "int" },
      is_active: { label: "Enabled", type: "bool" },
    },
  },
  currencies: {
    table: "currencies", pk: "code", pkType: "string", label: "Currencies", orderBy: "sort_order",
    fields: {
      code: { label: "ISO code", type: "text", pattern: "^[A-Z]{3}$", required: true, createOnly: true },
      name: { label: "Name", type: "text", required: true, max: 60 },
      symbol: { label: "Symbol", type: "text", required: true, max: 8 },
      decimals: { label: "Decimals", type: "int", min: 0, max: 4, required: true },
      razorpay_enabled: { label: "Accept via Razorpay", type: "bool", help: "Enable only if this currency is activated on your Razorpay account." },
      sort_order: { label: "Display order", type: "int" },
      is_active: { label: "Enabled", type: "bool" },
    },
  },
  languages: {
    table: "languages", pk: "code", pkType: "string", label: "Languages", orderBy: "sort_order",
    fields: {
      code: { label: "Code", type: "text", pattern: "^[a-z]{2}(-[A-Z]{2})?$", required: true, createOnly: true },
      name: { label: "Name", type: "text", required: true, max: 60 },
      native_name: { label: "Native name", type: "text", required: true, max: 60 },
      is_rtl: { label: "Right-to-left", type: "bool" },
      sort_order: { label: "Display order", type: "int" },
      is_active: { label: "Enabled", type: "bool" },
    },
  },
  shipping_zones: {
    table: "shipping_zones", pk: "code", pkType: "string", label: "Shipping zones", orderBy: "code",
    fields: { code: { label: "Code", type: "text", pattern: "^[A-Z0-9_]{2,30}$", required: true, createOnly: true }, name: { label: "Name", type: "text", required: true, max: 100 }, is_active: { label: "Enabled", type: "bool" } },
  },
  shipping_methods: {
    table: "shipping_methods", pk: "code", pkType: "string", label: "Shipping methods", orderBy: "sort_order",
    fields: {
      code: { label: "Code", type: "text", pattern: "^[a-z_]{2,20}$", required: true, createOnly: true },
      name: { label: "Name", type: "text", required: true, max: 60 },
      basis: { label: "Charged by", ...EN(["weight", "volume", "manual"]), required: true },
      carrier: { label: "Carrier", type: "text", max: 60 },
      sort_order: { label: "Display order", type: "int" },
      is_active: { label: "Enabled", type: "bool" },
    },
  },
  shipping_rate_rules: {
    table: "shipping_rate_rules", pk: "id", label: "Freight rates", orderBy: "dest_country, method_code",
    fields: {
      origin_country: { label: "Origin", ...CC, required: true },
      dest_country: { label: "Destination", ...CC },
      dest_zone: { label: "…or zone", type: "zone" },
      method_code: { label: "Method", type: "method", required: true },
      rate_basis: { label: "Basis", ...EN(["per_kg", "per_cbm", "flat"]), required: true },
      rate_usd: { label: "Rate (USD)", type: "decimal", required: true, min: 0 },
      min_charge_usd: { label: "Minimum charge (USD)", type: "decimal", min: 0 },
      volumetric_divisor: { label: "Volumetric divisor", type: "int", min: 1, help: "cm³ per kg, e.g. 5000 or 6000" },
      fuel_surcharge_pct: { label: "Fuel surcharge %", type: "decimal", min: 0 },
      remote_area_fee_usd: { label: "Remote-area fee (USD)", type: "decimal", min: 0 },
      transit_days_min: { label: "Transit days (min)", type: "int", min: 0 },
      transit_days_max: { label: "Transit days (max)", type: "int", min: 0 },
      missing_data_policy: { label: "If weight/dimensions missing", ...EN(["rfq_required", "admin_default"]), required: true },
      default_freight_usd: { label: "Default freight (USD)", type: "decimal", min: 0, help: "Used only with policy admin_default" },
      valid_from: { label: "Valid from", type: "date" },
      valid_to: { label: "Valid to", type: "date" },
      note: { label: "Note", type: "text", max: 500 },
      is_active: { label: "Enabled", type: "bool" },
    },
  },
  customs_rules: {
    table: "customs_rules", pk: "id", label: "Customs duties", orderBy: "dest_country, duty_type",
    fields: {
      name: { label: "Name", type: "text", required: true, max: 150 },
      origin_country: { label: "Origin of goods", ...CC },
      dest_country: { label: "Destination", ...CC, required: true },
      hs_prefix: { label: "HS/HTS prefix", type: "text", pattern: "^[0-9.]{2,14}$", max: 12 },
      attribute_code: { label: "Only if attribute", type: "text", max: 60 },
      attribute_value: { label: "…equals", type: "text", max: 255 },
      duty_type: { label: "Duty type", ...EN(["base", "section_301", "chapter_99", "anti_dumping", "countervailing", "safeguard", "excise", "other"]), required: true },
      rate_pct: { label: "Rate %", type: "decimal", min: 0, help: "Leave empty when the rate must be verified" },
      rate_status: { label: "Rate status", ...STATUS, required: true },
      additional_code: { label: "Additional code", type: "text", max: 40 },
      exporter: { label: "Exporter (specific rate)", type: "text", max: 150 },
      customer_message: { label: "Message shown to customer", type: "text", max: 500 },
      legal_reference: { label: "Reference / note", type: "text", max: 255 },
      valid_from: { label: "Effective from", type: "date" },
      valid_to: { label: "Effective to", type: "date" },
      is_active: { label: "Enabled", type: "bool" },
    },
  },
  tax_rules: {
    table: "tax_rules", pk: "id", label: "Taxes (VAT/GST)", orderBy: "dest_country",
    fields: {
      name: { label: "Name", type: "text", required: true, max: 100 },
      dest_country: { label: "Destination", ...CC, required: true },
      hs_prefix: { label: "HS prefix (optional)", type: "text", pattern: "^[0-9.]{2,14}$", max: 12 },
      rate_pct: { label: "Rate %", type: "decimal", required: true, min: 0 },
      basis: { label: "Charged on", ...EN(["customs_value_plus_duty", "goods", "goods_plus_freight"]), required: true },
      collected_at: { label: "Collected", ...EN(["import", "invoice"]), required: true },
      rate_status: { label: "Rate status", ...STATUS, required: true },
      valid_from: { label: "Effective from", type: "date" },
      valid_to: { label: "Effective to", type: "date" },
      note: { label: "Note", type: "text", max: 500 },
      is_active: { label: "Enabled", type: "bool" },
    },
  },
  withholding_rules: {
    table: "withholding_rules", pk: "id", label: "TDS / withholding", orderBy: "dest_country",
    fields: {
      name: { label: "Name", type: "text", required: true, max: 100 },
      dest_country: { label: "Country", ...CC, required: true },
      rate_pct: { label: "Rate %", type: "decimal", required: true, min: 0 },
      basis: { label: "Basis", ...EN(["goods", "invoice_total"]), required: true },
      threshold_usd: { label: "Threshold (USD)", type: "decimal", min: 0 },
      applies_to: { label: "Applies to", ...EN(["business", "all"]), required: true },
      note: { label: "Note", type: "text", max: 500 },
      is_active: { label: "Enabled", type: "bool" },
    },
  },
  insurance_rules: {
    table: "insurance_rules", pk: "id", label: "Insurance", orderBy: "dest_country",
    fields: {
      dest_country: { label: "Destination (empty = all)", ...CC },
      rate_pct: { label: "Rate %", type: "decimal", required: true, min: 0 },
      basis: { label: "Basis", ...EN(["goods", "goods_plus_freight"]), required: true },
      min_usd: { label: "Minimum (USD)", type: "decimal", min: 0 },
      note: { label: "Note", type: "text", max: 500 },
      is_active: { label: "Enabled", type: "bool" },
    },
  },
  handling_rules: {
    table: "handling_rules", pk: "id", label: "Handling", orderBy: "dest_country",
    fields: {
      name: { label: "Name", type: "text", required: true, max: 100 },
      dest_country: { label: "Destination (empty = all)", ...CC },
      method_code: { label: "Method (empty = all)", type: "method" },
      charge_type: { label: "Type", ...EN(["fixed", "percent"]), required: true },
      value: { label: "Value (USD or %)", type: "decimal", required: true, min: 0 },
      is_active: { label: "Enabled", type: "bool" },
    },
  },
  country_charge_rules: {
    table: "country_charge_rules", pk: "id", label: "Other charges", orderBy: "dest_country",
    fields: {
      name: { label: "Name", type: "text", required: true, max: 100 },
      dest_country: { label: "Destination", ...CC, required: true },
      charge_type: { label: "Type", ...EN(["fixed", "percent"]), required: true },
      value: { label: "Value (USD or %)", type: "decimal", required: true, min: 0 },
      payable_at: { label: "Paid", ...EN(["invoice", "import"]), required: true },
      is_active: { label: "Enabled", type: "bool" },
    },
  },
  incoterms: {
    table: "incoterms", pk: "code", pkType: "string", label: "Incoterms", orderBy: "sort_order",
    fields: {
      code: { label: "Code", type: "text", pattern: "^[A-Z]{3}$", required: true, createOnly: true },
      name: { label: "Name", type: "text", required: true, max: 80 },
      seller_pays_freight: { label: "IXITEK pays freight", type: "bool" },
      seller_pays_insurance: { label: "IXITEK pays insurance", type: "bool" },
      seller_pays_import: { label: "IXITEK pays import duties/taxes", type: "bool" },
      description: { label: "Description", type: "text", max: 500 },
      sort_order: { label: "Display order", type: "int" },
      is_active: { label: "Enabled", type: "bool" },
    },
  },
  payment_fee_rules: {
    table: "payment_fee_rules", pk: "id", label: "Payment fees (internal)", orderBy: "provider, scope",
    fields: {
      name: { label: "Name", type: "text", required: true, max: 100 },
      provider: { label: "Provider", type: "text", required: true, max: 30 },
      scope: { label: "Scope", ...EN(["domestic", "international"]), required: true },
      method: { label: "Payment method (empty = all)", type: "text", max: 30 },
      fee_pct: { label: "Fee %", type: "decimal", required: true, min: 0 },
      fee_tax_pct: { label: "Tax on fee %", type: "decimal", min: 0 },
      fixed_fee_usd: { label: "Fixed fee (USD)", type: "decimal", min: 0 },
      is_active: { label: "Enabled", type: "bool" },
    },
  },
};

module.exports = { ENTITIES };
