import {
  Cable,
  Radar,
  ServerCog,
  Users,
  UsersRound,
  Zap,
  Plug,
  PlugZap,
  Link2,
  Waypoints,
  GitBranch,
  SlidersHorizontal,
  Activity,
  Network,
  GitCompareArrows,
  Building2,
  Rows3,
  ArrowRight,
  ArrowUpRight,
  Menu,
  X,
  Search,
  ChevronDown,
  ChevronRight,
  Mail,
  Phone,
  MapPin,
  CheckCircle2,
  Check,
  ShieldCheck,
  Gauge,
  Sparkles,
  Layers,
  Globe2,
  Award,
  Handshake,
  Clock,
  TrendingUp,
  Filter,
  Send,
  Loader2,
  ExternalLink,
  ZoomIn,
  ChevronLeft,
  Quote,
  Boxes,
  Cpu,
  Wifi,
  ServerCrash,
  ClipboardList,
  BadgeCheck,
  Megaphone,
  Calculator,
  UploadCloud,
  Paperclip,
  FileText,
  Briefcase,
  Headset,
  Flag,
} from "lucide-react";

// LinkedIn is a brand mark, not part of the lucide icon set — provided as a
// custom inline SVG so it matches the stroke-based lucide icons visually.
function LinkedinMark({ className = "h-4 w-4", ...props }) {
  return (
    <svg viewBox="0 0 24 24" fill="currentColor" className={className} {...props}>
      <path d="M20.45 20.45h-3.56v-5.57c0-1.33-.02-3.04-1.85-3.04-1.85 0-2.14 1.45-2.14 2.94v5.67H9.34V9h3.42v1.56h.05c.48-.9 1.64-1.85 3.38-1.85 3.6 0 4.27 2.37 4.27 5.46zM5.34 7.43a2.07 2.07 0 1 1 0-4.13 2.07 2.07 0 0 1 0 4.13zM7.12 20.45H3.56V9h3.56z" />
    </svg>
  );
}

export const iconMap = {
  Linkedin: LinkedinMark,
  Cable,
  Radar,
  ServerCog,
  Users,
  UsersRound,
  Zap,
  Plug,
  PlugZap,
  Link2,
  Waypoints,
  GitBranch,
  SlidersHorizontal,
  Activity,
  Network,
  GitCompareArrows,
  Building2,
  Rows3,
  ArrowRight,
  ArrowUpRight,
  Menu,
  X,
  Search,
  ChevronDown,
  ChevronRight,
  Mail,
  Phone,
  MapPin,
  CheckCircle2,
  Check,
  ShieldCheck,
  Gauge,
  Sparkles,
  Layers,
  Globe2,
  Award,
  Handshake,
  Clock,
  TrendingUp,
  Filter,
  Send,
  Loader2,
  ExternalLink,
  ZoomIn,
  ChevronLeft,
  Quote,
  Boxes,
  Cpu,
  Wifi,
  ServerCrash,
  ClipboardList,
  BadgeCheck,
  Megaphone,
  Calculator,
  UploadCloud,
  Paperclip,
  FileText,
  Briefcase,
  Headset,
  Flag,
};

export function Icon({ name, ...props }) {
  const Cmp = iconMap[name] || Boxes;
  return <Cmp {...props} />;
}
